title: Goncalo Laranjo
#logo 
description: Student | Level 5 Cloud Computing, Analytics and Security for Industry FD 
             Goncalo Laranjo | 20 Years old | Portuguese Living in NI, Richhill
#show_downloads: true
theme: jekyll-theme-cayman
